services:
  nifi:
    image: apache/nifi:2.0.0-M4
    container_name: nifi
    hostname: nifi
    ports:
      - '8443:8443'
    volumes:
      - ./jar:/opt/jar
      - ./output:/tmp/input
      - ./nifi/properties:/opt/nifi/nifi-current/properties
    environment:
      NIFI_WEB_HTTPS_PORT: 8443
      SINGLE_USER_CREDENTIALS_USERNAME: nifi
      SINGLE_USER_CREDENTIALS_PASSWORD: apachenifi123
    networks:
      - network

  postgres:
    image: 'postgres:latest'
    hostname: postgres
    container_name: postgres
    expose:
      - '5432'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    networks:
      - network

  minio:
    image: 'minio/minio:latest'
    hostname: minio
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio-data:/data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server --console-address ":9001" /data
    networks:
      - network

  minio-mc:
    image: minio/mc:latest
    container_name: minio-mc
    depends_on:
      - minio
    ports:
      - "1977:1977"
    entrypoint: |
      sh -c "
      sleep 10 &&
      mc alias set myminio http://minio:9000 minio minio123 &&
      mc mb myminio/landing &&
      mc mb myminio/bronze &&
      mc mb myminio/silver &&
      mc mb myminio/gold &&
      mc mb myminio/frames &&
      mc policy set public myminio/frames
      "
    networks:
      - network

  rtmp:
    image: alfg/nginx-rtmp
    container_name: rtmp
    ports:
      - "1935:1935"
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf.template
      - ./output:/tmp/output
    networks:
      - network

  jupyter:
    image: yolov7-jupyter
    container_name: jupyter
    ports:
      - "8816:8816"
      - "22:22"
    volumes:
      - ./jupyter/notebook:/yolov7/notebook  # Monta o diretório atual para persistir os notebooks
    environment:
      - JUPYTER_ENABLE_LAB=yes         # Ativa o JupyterLab
    networks:
       - network

volumes:
  minio-data:
    driver: local

networks:
  network:
    name: network
    driver: bridge